version: '3'

services: 
  hey-db:
    image: postgres:13.1
    container_name: hey-db
    environment:
      - POSTGRES_USER=root 
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=hey-db
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - '5432:5432'
    networks:
      - default
      
  hey-app:
    container_name: hey
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3025:3025"
    command: pm2-runtime server.js
    external_links:
      - hey-db
    depends_on:
      - hey-db
    networks:
      - default

networks:
  default:
    name: hey